name: Cordviews Website

on:
  push:
    branches:
    - main
    
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 14
        - name: Installation
          run: yarn install --production
        - name: Build
          run: yarn build
